# Site settings
permalink: /blog/post/:title.html
paginate: 10
paginate_path: "/blog/page/:num"
title: Chester Holtz
email: chesterholtz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chester Holtz's website.  I am an aspiring scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chesterholtz.me" # the base hostname & protocol for your site
github_username:  choltz95

# Build settings
markdown: redcarpet
redcarpet:	
extensions: [smart, footnotes]
gems:      [jekyll-paginate]
